title: Harsha Sai Jagu
description: Data Scientist | Python, PySpark, ML, Big Data
baseurl: "" # leave empty
url: "https://harshasaijagu.github.io"

# Use remote theme instead of theme:
remote_theme: mmistakes/minimal-mistakes@4.24.0

# Navigation
nav:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Projects
    url: /projects/
  - title: Skills
    url: /skills/
  - title: Contact
    url: /contact/